### PR TITLE
2023 09 ucsb faculty

### PR DESCRIPTION
**Pull request by samanthacsik**
@hdolinh & @camilavargasp I've updated both section 9 (intro to git/github) & section 11 (merge conflicts). The preview looks good to me, but please feel free to let me know of other changes you need/want to see, if any

### CODE REVIEW

**Review by hdolinh — COMMENTED** [review]
Hey @samanthacsik these are really amazing updates thank you!! The new diagrams and clarified language is super helpful. 

My one note is in the Git + GitHub Collab lesson - I noticed you commented out the callout that talks about setting the pulling method using `git config pull.rebase false`. I would keep that in the setup instructions otherwise participants will get a warning when they try to pull.

Also if you want the two of us to practice demo-ing the examples before you teach the collab lesson on Friday lmk! We can quickly run through how we want to go back n forth between the screen sharing.

**Comment by samanthacsik** [comment]
@hdolinh thanks so much for reviewing!! I commented out that calluot in the Git + GitHub Collab lesson because it was redundant from the Git/GitHub Intro lesson (see [this section](https://learning.nceas.ucsb.edu/2023-09-ucsb-faculty/session_09.html#exercise-2-clone-your-repository-and-use-git-locally-in-rstudio)) -- I thought we didn't need to repeat this step, but please let me know if I'm mistaken and I can uncomment it in the Collab lesson.

I think I should be set on practice, but I was hoping you'd be up to demo at least the collab lesson on Friday :)

**Comment by hdolinh** [comment]
@samanthacsik Yes you're totally correct that we also do it in the Intro Git + GitHub lesson, but since we don't add the `--global` flag we're only specifying how to pull for that specific repo. I realize now I should have added language in the callout for this lesson that explains that and the reason why you wouldn't make it a global option is because some repos that you're a collaborator on might use a different pulling method like rebasing

**Comment by hdolinh** [comment]
@samanthacsik and yes, let's touchbase during one of the lunch hrs or breaks this week. :)

**Comment by samanthacsik** [comment]
okay, apologies for the back and forth, but I did the following:

- uncommented the callout in Ch 11
- added some explanatory text to both boxes (in Ch 9 & 11)

I'm still a little confused since it seems like we're using the `{firstname}_test` repo for the exercises in both chapters where we set this default (so my assumption would be that the default persists from the first time we do so in Ch 9?). That said, I've never actually set this before for any of my own repos, so I'm definitely pretty ignorant and likely wrong here 😅 

If you agree that it belongs still in both chapters, and that the text updates seem to sound right, feel free to merge! Otherwise, I can take another pass!

**Comment by hdolinh** [comment]
@samanthacsik These language edits look great - Thank you!! 

And the `git config` will be most relevant to the collaborators who are added to the `{firstname}_test` repos since it will be new repos for them. During delta, I saw the warning message come up often so it's good to have the info there as a reminder if any funky errors come up.

Going to merge your changes in now - thanks again!

**Pull request merged**
